name: Stop Application

on:
  workflow_dispatch:

jobs:
  stop:
    runs-on: ubuntu-latest

    steps:
      - name: Stop Application on EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "${EC2_KEY}" > private_key.pem
          chmod 600 private_key.pem
          
          echo "Connecting to EC2 instance to stop the application..."
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            echo "Connected to EC2 instance."
            cd /home/ubuntu/typescript-starter
            echo "Installing pm2 if not present..."
            # sudo npm install -g pm2
            echo "Stopping application with pm2..."
            ./node_modules/.bin/pm2 stop typescript-starter || true
            ./node_modules/.bin/pm2 delete typescript-starter || true
            ./node_modules/.bin/pm2 save || true
            echo "Application stopped."
          EOF
